[package]
name = "ssm_erc721"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.4"
openzeppelin = "0.18.0"

[dev-dependencies]
cairo_test = "2.8.4"

[[target.starknet-contract]]
sierra = true
casm = true